* Bu datasetinde maaşı etkileyen deneyimin yanında yaş da vardır.
* Simple  Linear Regression : y = b0+b1*x  --> maas = b0 + b1*deneyim
* Multiple LR : y= b0 +b1*x+ b2*x  +...  ---> maas = b0+b1*deneyim + b2*yas
* maas : dependent variable -- Bağımlı değişken
* deneyim , yaş : independent variable ---> bağımsız değişken
* LR mantığının aynısı amac = min (MSE)  B0,B1,B2 =?
* 

In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
df = pd.read_csv("multiple_linear_regression_dataset.csv", sep= ";")

In [9]:
df.head()

deneyim  maas  yas
0      0.5  2500   22
1      0.0  2250   21
2      1.0  2750   23
3      5.0  8000   25
4      8.0  9000   28

In [11]:
x = df.iloc[:,[0,2]].values
y = df.maas.values.reshape(-1,1)

In [13]:
x

array([[ 0.5, 22. ],
       [ 0. , 21. ],
       [ 1. , 23. ],
       [ 5. , 25. ],
       [ 8. , 28. ],
       [ 4. , 23. ],
       [15. , 35. ],
       [ 7. , 29. ],
       [ 3. , 22. ],
       [ 2. , 23. ],
       [12. , 32. ],
       [10. , 30. ],
       [14. , 34. ],
       [ 6. , 27. ]])

In [15]:
y

array([[ 2500],
       [ 2250],
       [ 2750],
       [ 8000],
       [ 9000],
       [ 6900],
       [20000],
       [ 8500],
       [ 6000],
       [ 3500],
       [15000],
       [13000],
       [18000],
       [ 7500]], dtype=int64)

In [17]:
multiple_linear_regression = LinearRegression()

In [21]:
multiple_linear_regression.fit(x,y)

LinearRegression()

In [23]:
print("b0:" , multiple_linear_regression.intercept_) 

b0: [10376.62747228]


In [25]:
print("b1 , b2 :" , multiple_linear_regression.coef_) 

b1 , b2 : [[1525.50072054 -416.72218625]]


In [29]:
#predict
multiple_linear_regression.predict(np.array([[10,35],[5,35]]))

array([[11046.35815877],
       [ 3418.85455609]])